src_path: /raid/data/DA_BrainDataset/siemens3/df_save.csv
tgt_path: /raid/data/DA_BrainDataset/philips3/df_save.csv

n_epochs: 15
gpu_id: [1]

model:
  num_classes: 2
  beta: 1.e-2
  ent_lambda: 5.e-3
  eta: 2.0

data: 
  test_size: 2.e-1
  batch_size: 30

checkpoint:
  dirpath: checkpoints
  monitor: val_miou
  mode: max

logger:
  name: DeepLab supervised
  project: FDA