src_path: /raid/data/DA_BrainDataset/siemens3/df_save.csv
tgt_path: /home/v_chernyy/thesis/pseudo_df.csv

n_epochs: 200
gpu_id: [1]

model:
  num_classes: 2
  beta: 1.e-1
  ent_lambda: 5.e-3
  eta: 2.0

data: 
  test_size: 2.e-1
  batch_size: 20

checkpoint:
  dirpath: checkpoints
  monitor: val_miou
  mode: max

logger:
  name: long_DeepLab self-supervised
  project: FDA