data: 
  # data_path: /home/v_chernyy/thesis/dataframes/philips3_cleaned.csv /home/v_chernyy/thesis/dataframes/philips3_cleaned.csv #/raid/data/DA_BrainDataset/siemens3/df_save.csv # /raid/data/DA_BrainDataset/philips3/df_save.csv
  data_path: /home/v_chernyy/thesis/dataframes/ge15.csv #/raid/data/DA_BrainDataset/philips3/df_save.csv
  batch_size: 50

model:
  n_chans_in: 1
  n_chans_out: 1

trainer:
    max_epochs: 200
    accelerator: gpu
    devices: [3]
    benchmark: true
    # limit_train_batches: 100
    check_val_every_n_epoch: 2
    enable_checkpointing: true

checkpoint:
  dirpath: checkpoints
  save_top_k: 1
  monitor: val Surface Dice
  mode: max
